// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: shipment.proto

package shipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber int64                  `protobuf:"varint,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	CurrentStatus   string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	Details         string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Amount          int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	DriverRevenue   int64                  `protobuf:"varint,7,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	Events          []*ShipmentEvent       `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *Shipment) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Shipment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() int64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *Shipment) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber int64                  `protobuf:"varint,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Details         string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Amount          int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	DriverRevenue   int64                  `protobuf:"varint,6,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CreateShipmentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() int64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type GetShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber int64                  `protobuf:"varint,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetShipmentRequest) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

type AddShipmentEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber int64                  `protobuf:"varint,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddShipmentEventRequest) Reset() {
	*x = AddShipmentEventRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventRequest) ProtoMessage() {}

func (x *AddShipmentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventRequest.ProtoReflect.Descriptor instead.
func (*AddShipmentEventRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *AddShipmentEventRequest) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

func (x *AddShipmentEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetShipmentEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber int64                  `protobuf:"varint,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentEventsRequest) Reset() {
	*x = GetShipmentEventsRequest{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsRequest) ProtoMessage() {}

func (x *GetShipmentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentEventsRequest) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

type ShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentResponse) Reset() {
	*x = ShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentResponse) ProtoMessage() {}

func (x *ShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentResponse.ProtoReflect.Descriptor instead.
func (*ShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *ShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type ShipmentEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ShipmentEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEventResponse) Reset() {
	*x = ShipmentEventResponse{}
	mi := &file_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEventResponse) ProtoMessage() {}

func (x *ShipmentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEventResponse.ProtoReflect.Descriptor instead.
func (*ShipmentEventResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *ShipmentEventResponse) GetEvent() *ShipmentEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetShipmentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ShipmentEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsResponse) Reset() {
	*x = GetShipmentEventsResponse{}
	mi := &file_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsResponse) ProtoMessage() {}

func (x *GetShipmentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *GetShipmentEventsResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\bshipment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\bShipment\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\x03R\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12%\n" +
	"\x0edriver_revenue\x18\a \x01(\x03R\rdriverRevenue\x12/\n" +
	"\x06events\x18\b \x03(\v2\x17.shipment.ShipmentEventR\x06events\"a\n" +
	"\rShipmentEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd5\x01\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\x03R\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12%\n" +
	"\x0edriver_revenue\x18\x06 \x01(\x03R\rdriverRevenue\"?\n" +
	"\x12GetShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\x03R\x0freferenceNumber\"\\\n" +
	"\x17AddShipmentEventRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\x03R\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"E\n" +
	"\x18GetShipmentEventsRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\x03R\x0freferenceNumber\"B\n" +
	"\x10ShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"F\n" +
	"\x15ShipmentEventResponse\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.shipment.ShipmentEventR\x05event\"L\n" +
	"\x19GetShipmentEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.shipment.ShipmentEventR\x06events2\xdf\x02\n" +
	"\x0fShipmentService\x12M\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a\x1a.shipment.ShipmentResponse\x12G\n" +
	"\vGetShipment\x12\x1c.shipment.GetShipmentRequest\x1a\x1a.shipment.ShipmentResponse\x12V\n" +
	"\x10AddShipmentEvent\x12!.shipment.AddShipmentEventRequest\x1a\x1f.shipment.ShipmentEventResponse\x12\\\n" +
	"\x11GetShipmentEvents\x12\".shipment.GetShipmentEventsRequest\x1a#.shipment.GetShipmentEventsResponseBDZBgithub.com/Rizabekus/shipment-grpc-service/proto/shipment;shipmentb\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shipment_proto_goTypes = []any{
	(*Shipment)(nil),                  // 0: shipment.Shipment
	(*ShipmentEvent)(nil),             // 1: shipment.ShipmentEvent
	(*CreateShipmentRequest)(nil),     // 2: shipment.CreateShipmentRequest
	(*GetShipmentRequest)(nil),        // 3: shipment.GetShipmentRequest
	(*AddShipmentEventRequest)(nil),   // 4: shipment.AddShipmentEventRequest
	(*GetShipmentEventsRequest)(nil),  // 5: shipment.GetShipmentEventsRequest
	(*ShipmentResponse)(nil),          // 6: shipment.ShipmentResponse
	(*ShipmentEventResponse)(nil),     // 7: shipment.ShipmentEventResponse
	(*GetShipmentEventsResponse)(nil), // 8: shipment.GetShipmentEventsResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_shipment_proto_depIdxs = []int32{
	1, // 0: shipment.Shipment.events:type_name -> shipment.ShipmentEvent
	9, // 1: shipment.ShipmentEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: shipment.ShipmentResponse.shipment:type_name -> shipment.Shipment
	1, // 3: shipment.ShipmentEventResponse.event:type_name -> shipment.ShipmentEvent
	1, // 4: shipment.GetShipmentEventsResponse.events:type_name -> shipment.ShipmentEvent
	2, // 5: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	3, // 6: shipment.ShipmentService.GetShipment:input_type -> shipment.GetShipmentRequest
	4, // 7: shipment.ShipmentService.AddShipmentEvent:input_type -> shipment.AddShipmentEventRequest
	5, // 8: shipment.ShipmentService.GetShipmentEvents:input_type -> shipment.GetShipmentEventsRequest
	6, // 9: shipment.ShipmentService.CreateShipment:output_type -> shipment.ShipmentResponse
	6, // 10: shipment.ShipmentService.GetShipment:output_type -> shipment.ShipmentResponse
	7, // 11: shipment.ShipmentService.AddShipmentEvent:output_type -> shipment.ShipmentEventResponse
	8, // 12: shipment.ShipmentService.GetShipmentEvents:output_type -> shipment.GetShipmentEventsResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
